#!/bin/sh
# `/sbin/setuser postgres` runs the given command as the user `postgres`.
# If you omit that part, the command will be run as root.
/etc/service/etcd/etcd -peer-addr 0.0.0.0:7001 -addr 0.0.0.0:4001 -name etcd-node1